# Generated by Django 5.0.6 on 2024-06-08 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата производства'),
            preserve_default=False,
        ),
    ]
