# Generated by Django 5.0.6 on 2024-06-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blogpost_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/blog/', verbose_name='Превью поста (изображение)'),
        ),
    ]
